"""skill column as string

Revision ID: 771ba1100259
Revises: 5e72caef6810
Create Date: 2023-07-19 10:48:21.807823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771ba1100259'
down_revision = '5e72caef6810'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
