"""changed to array

Revision ID: 7de2cf5b475c
Revises: 7202d8b80e09
Create Date: 2023-07-20 14:45:52.192526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de2cf5b475c'
down_revision = '7202d8b80e09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
