"""changed to string

Revision ID: 90421cf78ce1
Revises: 7de2cf5b475c
Create Date: 2023-07-20 14:49:18.089080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90421cf78ce1'
down_revision = '7de2cf5b475c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
